/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*- */
/* gen_wp6_charmap: build a Unicode -> WP6 (charset,index) reverse table by driving
 * libwpd's OWN WP6 decoder over every (charset, index) pair and inverting it.
 *
 * Guarantees our encoder agrees with libwpd's decoder, so extended characters
 * round-trip exactly. Output: WP6CharMap.inc (twin of gen_charmap.cpp / WP5).
 *
 *   clang++ gen_wp6_charmap.cpp -lwpd-0.10 -lrevenge-0.0 -o gen_wp6_charmap
 */

#include <cstdio>
#include <map>
#include <utility>

extern int extendedCharacterWP6ToUCS4(unsigned char character,
                                      unsigned char characterSet,
                                      const unsigned **chars);

int main()
{
	// WP6 character sets in PREFERENCE order (first hit wins). 1 = Multinational
	// (Latin letters) is primary; 4 = Typographic (dashes, quotes, bullet) next so
	// those canonical symbols win; then the specialized sets. 2 = Phonetic is
	// duplicate-heavy, so it is visited LAST. (0 = ASCII is handled directly.)
	const unsigned char charsets[] = {1, 4, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 2};

	std::map<unsigned, std::pair<unsigned char, unsigned char> > rev;

	for (unsigned ci = 0; ci < sizeof(charsets); ci++)
	{
		unsigned char cs = charsets[ci];
		for (int ch = 0; ch < 256; ch++)
		{
			const unsigned *chars = nullptr;
			int len = extendedCharacterWP6ToUCS4((unsigned char)ch, cs, &chars);
			if (len != 1 || !chars)
				continue;                // only clean single-codepoint mappings
			unsigned cp = chars[0];
			if (cp < 0x80 || cp == 0x20) // ASCII handled directly; skip ws fallback
				continue;
			if (rev.find(cp) == rev.end())
				rev[cp] = std::make_pair(cs, (unsigned char)ch);
		}
	}

	FILE *f = std::fopen("WP6CharMap.inc", "w");
	if (!f) { std::fprintf(stderr, "cannot write WP6CharMap.inc\n"); return 1; }
	std::fprintf(f, "/* Auto-generated by gen_wp6_charmap.cpp. Do not edit. */\n");
	std::fprintf(f, "/* Unicode code point -> WP6 (character set, index), sorted by cp. */\n");
	std::fprintf(f, "struct WP6CharMapEntry { unsigned cp; unsigned char charSet; unsigned char charIndex; };\n");
	std::fprintf(f, "static const WP6CharMapEntry s_wp6CharMap[] = {\n");
	for (auto &kv : rev)
		std::fprintf(f, "\t{0x%04x, %u, %u},\n", kv.first, kv.second.first, kv.second.second);
	std::fprintf(f, "};\n");
	std::fprintf(f, "static const unsigned s_wp6CharMapSize = %zu;\n", rev.size());
	std::fclose(f);

	std::fprintf(stderr, "Wrote WP6CharMap.inc with %zu entries\n", rev.size());
	return 0;
}
