/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*- */
/* gen_charmap: build a Unicode -> WP5 (charset,index) reverse table by driving
 * libwpd's OWN decoder over every (charset, index) pair and inverting it.
 *
 * This means our encoder is guaranteed consistent with libwpd's decoder, so
 * extended characters round-trip exactly. Output: WP5CharMap.inc
 *
 * Build (see gen_charmap step in build.sh):
 *   clang++ gen_charmap.cpp -lwpd-0.10 -lrevenge-0.0 -o gen_charmap
 */

#include <cstdio>
#include <map>
#include <utility>

// libwpd internal decoder (present in the static archive). Signature matches
// int extendedCharacterWP5ToUCS4(unsigned char, unsigned char, const unsigned**)
extern int extendedCharacterWP5ToUCS4(unsigned char character,
                                      unsigned char characterSet,
                                      const unsigned **chars);

int main()
{
	// WP5 character sets, in PREFERENCE order (first hit wins). Charset 2
	// (Multinational 2) is a duplicate-heavy secondary set, so it is visited
	// LAST: a character also available in a primary set (1 = Latin letters,
	// 4 = typographic symbols, etc.) uses that canonical set instead. This is
	// what fixes smart single quotes U+2018/U+2019 mapping to charset 4 (4,29 /
	// 4,28) rather than the charset-2 duplicates (2,11 / 2,19). Skip 0 = ASCII.
	const unsigned char charsets[] = {1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 2};

	// cp -> (charSet, index); first hit wins (lower charset preferred).
	std::map<unsigned, std::pair<unsigned char, unsigned char> > rev;

	for (unsigned ci = 0; ci < sizeof(charsets); ci++)
	{
		unsigned char cs = charsets[ci];
		for (int ch = 0; ch < 256; ch++)
		{
			const unsigned *chars = nullptr;
			int len = extendedCharacterWP5ToUCS4((unsigned char)ch, cs, &chars);
			// Only accept clean single-codepoint mappings.
			if (len != 1 || !chars)
				continue;
			unsigned cp = chars[0];
			// Skip ASCII (handled directly) and the decoder's whitespace
			// "last resort" fallback for unmapped pairs (cp == 0x20).
			if (cp < 0x80 || cp == 0x20)
				continue;
			if (rev.find(cp) == rev.end())
				rev[cp] = std::make_pair(cs, (unsigned char)ch);
		}
	}

	FILE *f = std::fopen("WP5CharMap.inc", "w");
	if (!f)
	{
		std::fprintf(stderr, "cannot write WP5CharMap.inc\n");
		return 1;
	}
	std::fprintf(f, "/* Auto-generated by gen_charmap.cpp. Do not edit. */\n");
	std::fprintf(f, "/* Unicode code point -> WP5 (character set, index), sorted by cp. */\n");
	std::fprintf(f, "struct WP5CharMapEntry { unsigned cp; unsigned char charSet; unsigned char charIndex; };\n");
	std::fprintf(f, "static const WP5CharMapEntry s_wp5CharMap[] = {\n");
	for (auto &kv : rev)
		std::fprintf(f, "\t{0x%04x, %u, %u},\n", kv.first, kv.second.first, kv.second.second);
	std::fprintf(f, "};\n");
	std::fprintf(f, "static const unsigned s_wp5CharMapSize = %zu;\n", rev.size());
	std::fclose(f);

	std::fprintf(stderr, "Wrote WP5CharMap.inc with %zu entries\n", rev.size());
	return 0;
}
